export const integrationCatalog = [
  { id: 'openrouter', name: 'OpenRouter', category: 'Gateway', mode: 'API', capabilities: ['Text', 'Reasoning', 'Code', 'Model families'], note: 'One key loads the live OpenRouter model network.' },
  { id: 'openai', name: 'ChatGPT / OpenAI', category: 'Assistant', mode: 'API', capabilities: ['Text', 'Reasoning', 'Code', 'Images'], note: 'Available through OpenRouter or an optional direct OpenAI key.' },
  { id: 'microsoft-copilot', name: 'Microsoft Copilot', category: 'Assistant', mode: 'External', capabilities: ['Text', 'Research', 'Microsoft ecosystem'], note: 'External assistant workflow; no consumer-account scraping.' },
  { id: 'anthropic', name: 'Claude', category: 'Assistant', mode: 'API', capabilities: ['Text', 'Reasoning', 'Documents', 'Code'], note: 'Available through OpenRouter or an optional direct Anthropic key.' },
  { id: 'gemini', name: 'Google Gemini', category: 'Assistant', mode: 'API', capabilities: ['Text', 'Reasoning', 'Multimodal'], note: 'Available through OpenRouter or an optional direct Gemini key.' },
  { id: 'notebooklm', name: 'NotebookLM', category: 'Research', mode: 'External', capabilities: ['Documents', 'Study guides', 'Audio overviews'], note: 'External Google research workspace.' },
  { id: 'google-ai-studio', name: 'Google AI Studio', category: 'Developer', mode: 'External', capabilities: ['Prompt testing', 'Gemini models'], note: 'Developer workspace for Gemini API projects.' },
  { id: 'xai', name: 'Grok / xAI', category: 'Assistant', mode: 'API', capabilities: ['Text', 'Reasoning', 'Code'], note: 'Available through OpenRouter or an optional direct xAI key.' },
  { id: 'perplexity', name: 'Perplexity', category: 'Research', mode: 'API', capabilities: ['Research', 'Web-grounded answers'], note: 'Available through OpenRouter when listed, or an optional direct key.' },
  { id: 'mistral', name: 'Mistral AI', category: 'Assistant', mode: 'API', capabilities: ['Text', 'Reasoning', 'Code'], note: 'Available through OpenRouter or an optional direct Mistral key.' },
  { id: 'groq', name: 'Groq', category: 'Inference', mode: 'API', capabilities: ['Fast text', 'Code', 'Open models'], note: 'Low-latency OpenAI-compatible inference.' },
  { id: 'deepseek', name: 'DeepSeek', category: 'Assistant', mode: 'API', capabilities: ['Reasoning', 'Code', 'Text'], note: 'Available through OpenRouter or an optional direct provider key.' },
  { id: 'huggingface', name: 'Hugging Face', category: 'Inference', mode: 'API', capabilities: ['Open models', 'Text', 'Code'], note: 'Inference Providers router.' },
  { id: 'cloudflare', name: 'Cloudflare Workers AI', category: 'Inference', mode: 'API', capabilities: ['Open models', 'Text'], note: 'Cloud-hosted model inference.' },
  { id: 'ollama', name: 'Ollama', category: 'Local', mode: 'API', capabilities: ['Private local models', 'Text', 'Code'], note: 'Requires a server-reachable Ollama URL.' },
  { id: 'meta', name: 'Meta AI / Llama', category: 'Model family', mode: 'Gateway', capabilities: ['Text', 'Code', 'Open weights'], note: 'Available through OpenRouter, Hugging Face, Groq, Cloudflare or Ollama.' },
  { id: 'qwen', name: 'Qwen', category: 'Model family', mode: 'Gateway', capabilities: ['Text', 'Reasoning', 'Code'], note: 'Available through gateways and local runtimes.' },
  { id: 'openai-images', name: 'OpenAI Image Generation', category: 'Image', mode: 'API', capabilities: ['Images', 'Editing'], note: 'Available through OpenRouter image models or an optional direct OpenAI key.' },
  { id: 'gemini-images', name: 'Gemini Image Generation', category: 'Image', mode: 'Gateway', capabilities: ['Images', 'Multimodal'], note: 'Available through OpenRouter image models when supported.' },
  { id: 'meta-images', name: 'Meta AI Images', category: 'Image', mode: 'External', capabilities: ['Images', 'Social'], note: 'External Meta AI workflow.' },
  { id: 'recraft', name: 'Recraft', category: 'Image & Design', mode: 'External', capabilities: ['Vectors', 'Icons', 'Images'], note: 'Use external workspace or a custom webhook/API arrangement.' },
  { id: 'ideogram', name: 'Ideogram', category: 'Image & Design', mode: 'External', capabilities: ['Images', 'Readable text'], note: 'Use external workspace or connect through a supported API account.' },
  { id: 'adobe-firefly', name: 'Adobe Firefly', category: 'Image & Video', mode: 'External', capabilities: ['Images', 'Video', 'Editing'], note: 'Enterprise/developer access varies by Adobe plan.' },
  { id: 'canva', name: 'Canva AI', category: 'Design', mode: 'External', capabilities: ['Design', 'Presentations', 'Social'], note: 'Listed as an external workflow; not scraped.' },
  { id: 'designer', name: 'Microsoft Designer', category: 'Design', mode: 'External', capabilities: ['Images', 'Social graphics'], note: 'External workflow.' },
  { id: 'playground', name: 'Playground AI', category: 'Image', mode: 'External', capabilities: ['Images', 'Editing'], note: 'External workflow.' },
  { id: 'stablediffusion', name: 'Stable Diffusion', category: 'Image', mode: 'Gateway', capabilities: ['Images', 'Local generation'], note: 'Available through supported OpenRouter image models or optional media connectors.' },
  { id: 'flux', name: 'FLUX', category: 'Image', mode: 'Gateway', capabilities: ['Images'], note: 'Available through supported OpenRouter image models or optional media connectors.' },
  { id: 'comfyui', name: 'ComfyUI', category: 'Image & Video', mode: 'Webhook', capabilities: ['Advanced workflows'], note: 'Connect a deployed ComfyUI workflow through the generic media webhook.' },
  { id: 'capcut', name: 'CapCut AI', category: 'Video', mode: 'External', capabilities: ['Editing', 'Captions', 'Voice'], note: 'External workflow; consumer UI automation is intentionally avoided.' },
  { id: 'meta-vibes', name: 'Meta AI Vibes', category: 'Video', mode: 'External', capabilities: ['Short AI video', 'Social'], note: 'External Meta AI workflow.' },
  { id: 'pika', name: 'Pika', category: 'Video', mode: 'External', capabilities: ['Video effects', 'Generation'], note: 'External or custom webhook integration.' },
  { id: 'kling', name: 'Kling AI', category: 'Video', mode: 'External', capabilities: ['Text-to-video', 'Image-to-video'], note: 'External or custom webhook integration.' },
  { id: 'luma', name: 'Luma Dream Machine', category: 'Video', mode: 'External', capabilities: ['Video generation'], note: 'External or custom webhook integration.' },
  { id: 'hailuo', name: 'Hailuo AI', category: 'Video', mode: 'External', capabilities: ['Video generation'], note: 'External workflow.' },
  { id: 'pixverse', name: 'PixVerse', category: 'Video', mode: 'External', capabilities: ['Video generation', 'Effects'], note: 'External workflow.' },
  { id: 'replicate', name: 'Replicate', category: 'Media Gateway', mode: 'API', capabilities: ['Images', 'Video', 'Audio', 'Models'], note: 'Generic prediction support for configured model versions.' },
  { id: 'elevenlabs', name: 'ElevenLabs', category: 'Audio', mode: 'API', capabilities: ['Voice', 'Speech', 'Sound effects'], note: 'Text-to-speech is built in when configured.' },
  { id: 'suno', name: 'Suno', category: 'Music', mode: 'External', capabilities: ['Music', 'Instrumentals'], note: 'External or custom webhook; commercial terms depend on plan.' },
  { id: 'udio', name: 'Udio', category: 'Music', mode: 'External', capabilities: ['Music', 'Remixing'], note: 'External workflow.' },
  { id: 'adobe-podcast', name: 'Adobe Podcast', category: 'Audio', mode: 'External', capabilities: ['Voice cleanup'], note: 'External workflow.' },
  { id: 'gamma', name: 'Gamma', category: 'Presentation', mode: 'External', capabilities: ['Slides', 'Documents', 'Web pages'], note: 'External workflow or custom automation.' },
  { id: 'grammarly', name: 'Grammarly', category: 'Writing', mode: 'External', capabilities: ['Grammar', 'Rewriting'], note: 'External workflow.' },
  { id: 'quillbot', name: 'QuillBot', category: 'Writing', mode: 'External', capabilities: ['Paraphrasing', 'Summaries'], note: 'External workflow.' },
  { id: 'deepl', name: 'DeepL', category: 'Translation', mode: 'External', capabilities: ['Translation', 'Writing'], note: 'Can be added through a custom provider or webhook.' },
  { id: 'elicit', name: 'Elicit', category: 'Research', mode: 'External', capabilities: ['Academic research'], note: 'External workflow.' },
  { id: 'consensus', name: 'Consensus', category: 'Research', mode: 'External', capabilities: ['Scientific research'], note: 'External workflow.' },
  { id: 'researchrabbit', name: 'ResearchRabbit', category: 'Research', mode: 'External', capabilities: ['Literature discovery'], note: 'External workflow.' },
  { id: 'github-copilot', name: 'GitHub Copilot', category: 'Coding', mode: 'External', capabilities: ['Coding', 'Repository work'], note: 'Runs in GitHub/IDE rather than as a general public web API.' },
  { id: 'gemini-code-assist', name: 'Gemini Code Assist', category: 'Coding', mode: 'External', capabilities: ['Coding', 'IDE assistance'], note: 'External developer workflow.' },
  { id: 'gemini-cli', name: 'Gemini CLI', category: 'Coding', mode: 'External', capabilities: ['Terminal agent', 'Coding'], note: 'Runs in a developer terminal rather than this hosted browser.' },
  { id: 'lm-studio', name: 'LM Studio', category: 'Local', mode: 'Gateway', capabilities: ['Local models', 'OpenAI-compatible server'], note: 'Can be connected through CUSTOM_PROVIDERS_JSON when its server is securely reachable.' },
  { id: 'cursor', name: 'Cursor', category: 'Coding', mode: 'External', capabilities: ['Coding', 'Agents'], note: 'Desktop coding environment.' },
  { id: 'replit', name: 'Replit', category: 'Coding', mode: 'External', capabilities: ['Apps', 'Deployment'], note: 'External coding workspace.' },
  { id: 'amazon-q', name: 'Amazon Q Developer', category: 'Coding', mode: 'External', capabilities: ['Coding', 'AWS'], note: 'External developer workflow.' },
  { id: 'custom-webhook', name: 'Custom Webhook / MCP Bridge', category: 'Universal', mode: 'Webhook', capabilities: ['Any authorized service'], note: 'Future-proof connector for services with private or changing APIs.' }
];

export const textProviderDefinitions = [
  { id: 'openrouter', name: 'OpenRouter', env: 'OPENROUTER_API_KEY', modelEnv: 'OPENROUTER_MODEL', model: 'openrouter/free', type: 'openai', baseUrl: 'https://openrouter.ai/api/v1', strengths: ['general', 'creative', 'reasoning', 'code', 'research'], priority: 7 },
  { id: 'openai', name: 'OpenAI', env: 'OPENAI_API_KEY', modelEnv: 'OPENAI_MODEL', model: 'gpt-5-mini', type: 'openai-responses', baseUrl: 'https://api.openai.com/v1', strengths: ['general', 'reasoning', 'code', 'creative'], priority: 10 },
  { id: 'anthropic', name: 'Claude', env: 'ANTHROPIC_API_KEY', modelEnv: 'ANTHROPIC_MODEL', model: 'claude-sonnet-4-5', type: 'anthropic', baseUrl: 'https://api.anthropic.com/v1', strengths: ['reasoning', 'writing', 'documents', 'code'], priority: 9 },
  { id: 'gemini', name: 'Gemini', env: 'GEMINI_API_KEY', modelEnv: 'GEMINI_MODEL', model: 'gemini-3.6-flash', type: 'gemini', baseUrl: 'https://generativelanguage.googleapis.com/v1beta', strengths: ['general', 'reasoning', 'creative', 'multimodal'], priority: 8 },
  { id: 'xai', name: 'Grok', env: 'XAI_API_KEY', modelEnv: 'XAI_MODEL', model: 'grok-4-fast', type: 'openai', baseUrl: 'https://api.x.ai/v1', strengths: ['general', 'reasoning', 'code', 'research'], priority: 8 },
  { id: 'perplexity', name: 'Perplexity', env: 'PERPLEXITY_API_KEY', modelEnv: 'PERPLEXITY_MODEL', model: 'sonar', type: 'openai', baseUrl: 'https://api.perplexity.ai', strengths: ['research', 'current', 'sources'], priority: 9 },
  { id: 'mistral', name: 'Mistral', env: 'MISTRAL_API_KEY', modelEnv: 'MISTRAL_MODEL', model: 'mistral-small-latest', type: 'openai', baseUrl: 'https://api.mistral.ai/v1', strengths: ['general', 'code', 'reasoning'], priority: 7 },
  { id: 'groq', name: 'Groq', env: 'GROQ_API_KEY', modelEnv: 'GROQ_MODEL', model: 'llama-3.3-70b-versatile', type: 'openai', baseUrl: 'https://api.groq.com/openai/v1', strengths: ['fast', 'general', 'code'], priority: 6 },
  { id: 'deepseek', name: 'DeepSeek', env: 'DEEPSEEK_API_KEY', modelEnv: 'DEEPSEEK_MODEL', model: 'deepseek-chat', type: 'openai', baseUrl: 'https://api.deepseek.com/v1', strengths: ['reasoning', 'code', 'general'], priority: 8 },
  { id: 'huggingface', name: 'Hugging Face', env: 'HF_TOKEN', modelEnv: 'HF_MODEL', model: 'meta-llama/Llama-3.1-8B-Instruct', type: 'openai', baseUrl: 'https://router.huggingface.co/v1', strengths: ['open', 'general', 'code'], priority: 5 },
  { id: 'cloudflare', name: 'Cloudflare AI', env: 'CLOUDFLARE_API_TOKEN', modelEnv: 'CLOUDFLARE_MODEL', model: '@cf/meta/llama-3.3-70b-instruct-fp8-fast', type: 'cloudflare', strengths: ['open', 'general', 'fast'], priority: 5 },
  { id: 'ollama', name: 'Ollama', env: 'OLLAMA_BASE_URL', modelEnv: 'OLLAMA_MODEL', model: 'llama3.2', type: 'ollama', strengths: ['private', 'general', 'code'], priority: 6 }
];
