import { readJsonBody } from '../server/lib/http.js';
import { authorize, rateLimit, cleanString } from '../server/lib/security.js';

const CRC_TABLE = (() => {
  const table = new Uint32Array(256);
  for (let n = 0; n < 256; n += 1) {
    let c = n;
    for (let k = 0; k < 8; k += 1) c = (c & 1) ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
    table[n] = c >>> 0;
  }
  return table;
})();

function crc32(buffer) {
  let c = 0xffffffff;
  for (const byte of buffer) c = CRC_TABLE[(c ^ byte) & 0xff] ^ (c >>> 8);
  return (c ^ 0xffffffff) >>> 0;
}

function safePath(value, fallback) {
  const path = String(value || '').replaceAll('\\', '/').replace(/^\/+/, '').replace(/\.\.(\/|$)/g, '').trim();
  if (!path || path.length > 160 || /[\0<>:"|?*]/.test(path)) return fallback;
  return path;
}

function u16(value) {
  const buffer = Buffer.alloc(2);
  buffer.writeUInt16LE(value & 0xffff, 0);
  return buffer;
}

function u32(value) {
  const buffer = Buffer.alloc(4);
  buffer.writeUInt32LE(value >>> 0, 0);
  return buffer;
}

function buildZip(files) {
  const localParts = [];
  const centralParts = [];
  let offset = 0;

  files.forEach((file, index) => {
    const name = Buffer.from(file.path, 'utf8');
    const data = file.buffer ? Buffer.from(file.buffer) : Buffer.from(file.content, 'utf8');
    const crc = crc32(data);
    const localHeader = Buffer.concat([
      u32(0x04034b50), u16(20), u16(0x0800), u16(0), u16(0), u16(0),
      u32(crc), u32(data.length), u32(data.length), u16(name.length), u16(0), name
    ]);
    localParts.push(localHeader, data);

    const centralHeader = Buffer.concat([
      u32(0x02014b50), u16(20), u16(20), u16(0x0800), u16(0), u16(0), u16(0),
      u32(crc), u32(data.length), u32(data.length), u16(name.length), u16(0), u16(0),
      u16(0), u16(0), u32(0), u32(offset), name
    ]);
    centralParts.push(centralHeader);
    offset += localHeader.length + data.length;
  });

  const central = Buffer.concat(centralParts);
  const end = Buffer.concat([
    u32(0x06054b50), u16(0), u16(0), u16(files.length), u16(files.length),
    u32(central.length), u32(offset), u16(0)
  ]);
  return Buffer.concat([...localParts, central, end]);
}


function hasFile(files, path) {
  return files.some((file) => file.path.toLowerCase() === path.toLowerCase());
}

function validSiteUrl(value = '') {
  try {
    const url = new URL(String(value || '').trim());
    return ['http:', 'https:'].includes(url.protocol) ? url.href.replace(/\/$/, '') : '';
  } catch { return ''; }
}

function ensureProductionFiles(files, options = {}) {
  const output = [...files];
  const staticSite = hasFile(output, 'index.html');
  if (!staticSite) return output;
  const projectName = cleanString(options.projectName, 80) || 'OmniFusion website';
  const siteUrl = validSiteUrl(options.siteUrl);
  if (!hasFile(output, 'robots.txt')) output.push({ path: 'robots.txt', content: 'User-agent: *\nAllow: /\n' });
  if (!hasFile(output, '404.html')) output.push({ path: '404.html', content: `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Page not found · ${projectName}</title></head><body><main><h1>Page not found</h1><p>The page you requested does not exist.</p><p><a href="./index.html">Return home</a></p></main></body></html>` });
  if (!hasFile(output, 'favicon.svg')) output.push({ path: 'favicon.svg', content: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64"><rect width="64" height="64" rx="16" fill="#111827"/><path d="M18 42V22h28v20H18Zm6-6h16v-8H24v8Z" fill="#fff"/></svg>' });
  if (!hasFile(output, 'README.md')) output.push({ path: 'README.md', content: `# ${projectName}

Production-ready static website generated by OmniFusion Prime Intelligence.

## Deploy

Upload every file in this folder to a static host such as Vercel, Netlify, GitHub Pages, or conventional web hosting. Keep the relative paths unchanged.

## Before launch

- Confirm all business facts and contact destinations.
- Replace any clearly labeled placeholder assets.
- Add the final public domain to sitemap.xml if it was not known during generation.
- Test the contact method on a real device.
` });
  if (siteUrl && !hasFile(output, 'sitemap.xml')) output.push({ path: 'sitemap.xml', content: `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"><url><loc>${siteUrl}/</loc></url></urlset>
` });
  if (!hasFile(output, 'release-report.json')) output.push({ path: 'release-report.json', content: JSON.stringify({ projectName, packagedAt: new Date().toISOString(), generatedSupportFiles: true, validation: options.validation || null }, null, 2) });
  return output;
}

export default async function handler(req, res) {
  if (req.method !== 'POST') {
    res.status(405).json({ error: 'Use POST.' });
    return;
  }
  const access = authorize(req);
  if (!access.ok) {
    res.status(access.status).json({ error: access.error });
    return;
  }
  const limiter = rateLimit(req);
  if (!limiter.ok) {
    res.status(limiter.status).json({ error: limiter.error });
    return;
  }

  const body = await readJsonBody(req);
  let files = [];
  const seen = new Set();
  for (const item of Array.isArray(body.files) ? body.files : []) {
    if (!item || typeof item.content !== 'string') continue;
    const path = safePath(item.path, `file-${files.length + 1}.txt`);
    if (seen.has(path)) continue;
    seen.add(path);
    files.push({ path, content: item.content.slice(0, 160000) });
    if (files.length >= 40) break;
  }
  for (const item of Array.isArray(body.media) ? body.media : []) {
    if (!item || typeof item.contentBase64 !== 'string' || !item.contentBase64) continue;
    const path = safePath(item.path, `asset-${files.length + 1}.bin`);
    if (seen.has(path)) continue;
    let buffer;
    try { buffer = Buffer.from(item.contentBase64, 'base64'); } catch { continue; }
    if (!buffer.length || buffer.length > 1_500_000) continue;
    seen.add(path);
    files.push({ path, buffer });
    if (files.length >= 44) break;
  }
  const packageMode = cleanString(body.packageMode, 30) === 'review' ? 'review' : 'release';
  if (packageMode === 'release') files = ensureProductionFiles(files, {
    projectName: cleanString(body.projectName, 80),
    siteUrl: cleanString(body.siteUrl, 2000),
    validation: body.validation && typeof body.validation === 'object' ? body.validation : null
  });
  if (!files.length) {
    res.status(400).json({ error: 'No files were supplied.' });
    return;
  }
  const total = files.reduce((sum, file) => sum + (file.buffer ? file.buffer.length : Buffer.byteLength(file.content)), 0);
  if (total > 4_500_000) {
    res.status(413).json({ error: 'Project is too large to package in this deployment.' });
    return;
  }

  const projectName = (cleanString(body.projectName, 80) || 'omnifusion-project')
    .toLowerCase().replace(/[^a-z0-9-_]+/g, '-').replace(/^-+|-+$/g, '') || 'omnifusion-project';
  const zip = buildZip(files);
  res.status(200);
  res.setHeader('Content-Type', 'application/zip');
  res.setHeader('Content-Disposition', `attachment; filename="${projectName}.zip"`);
  res.setHeader('Content-Length', String(zip.length));
  res.setHeader('Cache-Control', 'no-store');
  res.end(zip);
}

export { buildZip, crc32, ensureProductionFiles };
